import Config
config :ash, policies: [show_policy_breakdowns?: true]

config :skeet_deleter, SkeetDeleterWeb.Endpoint,
  url: [host: "6e1551ee087b.ngrok-free.app", port: 443, scheme: "https"],
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "fxjJcpgt5bxPkJK78cftA2g/5SP3Z+rGuL9ovaAqYZgduzlJBUIKRzKc9rdctD5q",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:skeet_deleter, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:skeet_deleter, ~w(--watch)]}
  ]

# Configure your database
config :skeet_deleter, SkeetDeleter.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "skeet_deleter_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :skeet_deleter, SkeetDeleterWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/skeet_deleter_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :skeet_deleter, dev_routes: true, token_signing_secret: "MJh0f4VdtqAoU6Jbog2fCGaRVj1wn2a9"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
