defmodule SkeetDeleter.Repo.Migrations.StoreUserTokensOnUserResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # drop constraint("users", "users_pkey")

    alter table(:users) do
      remove :encrypted_app_key
      remove :email
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
      add :did, :text, null: false, primary_key: false
      add :access_token, :text
      add :refresh_token, :text
      add :app_key, :text
    end

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    create unique_index(:users, [:did], name: "users_unique_did_index")
  end

  def down do
    drop constraint("users", "users_pkey")

    drop_if_exists unique_index(:users, [:did], name: "users_unique_did_index")

    create unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :app_key
      remove :refresh_token
      remove :access_token
      remove :did
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      add :email, :citext, null: false
      add :encrypted_app_key, :binary
    end
  end
end
