defmodule SkeetDeleter.Repo.Migrations.AddTokenExpiration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :did, :text
      add :token_expiration, :utc_datetime
    end
  end

  def down do
    alter table(:users) do
      remove :token_expiration
      modify :did, :text
    end
  end
end
