defmodule SkeetDeleter.Repo.Migrations.SetDefaultRole do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :role, :text, default: "subscriber"
    end
  end

  def down do
    alter table(:users) do
      modify :role, :text, default: nil
    end
  end
end
