defmodule SkeetDeleter.Repo.Migrations.AddUserHandle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :handle, :text
    end
  end

  def down do
    alter table(:users) do
      remove :handle
    end
  end
end
