defmodule SkeetDeleter.Repo.Migrations.RenameFrequencyToMaxAge do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:actions), :frequency, to: :max_age
  end

  def down do
    rename table(:actions), :max_age, to: :frequency
  end
end
