defmodule SkeetDeleter.Repo.Migrations.AddRecordTypesAndFrequencyToAction do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:actions) do
      add :record_types, {:array, :text}
      add :frequency, :bigint
    end
  end

  def down do
    alter table(:actions) do
      remove :frequency
      remove :record_types
    end
  end
end
