defmodule SkeetDeleter.Repo.Migrations.UseBooleansForActionRecordTargetTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:actions) do
      remove :record_types
      add :posts_without_images, :boolean, default: false
      add :posts_with_images, :boolean, default: false
      add :reposts, :boolean, default: false
      add :likes, :boolean, default: false
    end
  end

  def down do
    alter table(:actions) do
      remove :likes
      remove :reposts
      remove :posts_with_images
      remove :posts_without_images
      add :record_types, {:array, :text}
    end
  end
end
