defmodule SkeetDeleter.Repo.Migrations.EncryptTokensAtRest do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :refresh_token
      remove :access_token
      add :encrypted_access_token, :binary
      add :encrypted_refresh_token, :binary
    end
  end

  def down do
    alter table(:users) do
      remove :encrypted_refresh_token
      remove :encrypted_access_token
      add :access_token, :text
      add :refresh_token, :text
    end
  end
end
