defmodule SkeetDeleter.Repo.Migrations.RemoveAppKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :app_key
    end
  end

  def down do
    alter table(:users) do
      add :app_key, :text
    end
  end
end
